#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ll='ls -la'
alias e='emacsclient -nw'

export VISUAL=emacsclient
export EDITOR=emacsclient

path=(
  /usr/local/opt/ncurses/bin(N-/)
  /usr/local/Cellar/openssl/1.0.2j/bin
  $HOME/Applications/homebrew/bin
  $HOME/.rbenv/bin
  $HOME/.yarn/bin
  $HOME/.local/bin
  $HOME/bin
  $path
)

export HOMEBREW_CACHE=$HOME/Applications/homebrew/cache
export HOMEBREW_CASK_OPTS="--appdir=$HOME/Applications"

eval "$(rbenv init -)"
eval "$(nodenv init -)"
eval "$(direnv hook zsh)"

setopt nonomatch
