#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ls="gls --color=always"
alias ll='ls -l'
alias e='emacsclient -nw'

export VISUAL=emacsclient
export EDITOR=emacsclient

path=(
  $HOME/Applications/homebrew/bin
  $HOME/Applications/homebrew/opt/coreutils/libexec/gnubin
  $HOME/.rbenv/bin
  $path
)

# color setting
if type dircolors >/dev/null; then
  eval `dircolors $HOME/.dir_colors`
fi

export HOMEBREW_CACHE=$HOME/Applications/homebrew/cache
export HOMEBREW_CASK_OPTS="--appdir=$HOME/Applications"

eval "$(rbenv init -)"
eval "$(nodenv init -)"
eval "$(direnv hook zsh)"

setopt nonomatch

rimrafconf() {
  echo "rm -rf $@ ??"
  read input

  if [ -z $input ] ; then
    echo "must type y or n"
    rimrafconf
  elif [ $input = 'yes' ] || [ $input = 'YES' ] || [ $input = 'y' ] ; then
    echo "rm -rf $@ ..."
  elif [ $input = 'no' ] || [ $input = 'NO' ] || [ $input = 'n' ] ; then
    echo "cancel"
    return
  else
    echo "must type y or n"
    rimrafconf
  fi

  command rm -rf $@
}

peco-select-history() {
  local tac
  if which tac > /dev/null; then
    tac="tac"
  else
    tac="tail -r"
  fi
  BUFFER=`history -n 1 | tac  | awk '!a[$0]++' | peco`
  CURSOR=$#BUFFER
  zle reset-prompt
}

zle -N peco-select-history
bindkey '^r' peco-select-history
